Create README.md file
AgileVentures/WebsiteTwo pull request #9
Opened 2020-08-05 15:33 UTC by riccardo-giomi

* added "Prerequisites" section, pointing to Gatsby's tutorial
* added "Getting started" instructions;
* copied "History" section from WSO REAME file, updated it a little;

2020-08-07 14:13 UTC, aonomike commented
Looks good to me, just add a few comments.

2020-08-08 17:53 UTC, aonomike requested changes
Looks good to me, just had a few suggestions.

2020-08-08 17:53 UTC, aonomike commented on README.md
> +## Quick start
Maybe we need to ask them to fork the repository first, if they are not yet added to the repository, or maybe reach out if they wanna be added as part of the team in github, otherwise, the would not be able to push.

2020-08-08 17:53 UTC, aonomike commented on README.md
> +yarn
Also maybe they need to know that they need to get set up with node, and npm or yarn, that is if they are very new

2020-08-08 17:53 UTC, aonomike commented on README.md
> +## History
do we really need the history as part of the read me? maybe we can link to a HISTORY.md file?

2020-08-08 19:03 UTC, riccardo-giomi commented on README.md
> +## Quick start
I would add those instructions on that on the CONTRIBUTING.md file. There is a separate card about adding more information in that file in the [project](https://github.com/AgileVentures/WebsiteTwo/projects).

This file is missing a link to the CONTRIBUTING file, though, I'll merge from develop and add it in.

2020-08-08 19:07 UTC, riccardo-giomi commented on README.md
> +yarn
Under **Requirements** there is a link to the Gatsby "Set Up Your Development Environment" page, where there are detailed instructions about installing node and more.
Should I add more text in there naming the requirements explicitly?

2020-08-08 19:09 UTC, riccardo-giomi commented on README.md
> +## History
It was in the README.md for WebsiteOne. The idea is that it goes to the first page of the project in Github, so the README is like the front-page for AV in there. I'd keep it.

2020-08-12 14:57 UTC, riccardo-giomi commented
A strange merge along the line confused things, closing this PR and starting again.

2020-08-12 14:57 UTC, closed without merging